from functions import squared
from exception import keyError

# for i in range(10):
#     print(f"{i} squared is {squared(i)}")

keyError()